In [52]:
#Bron https://www.kaggle.com/shatiel/practicing-playing-with-mnist-decision-tree
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn import tree
from sklearn import metrics

train = pd.read_csv("./train.csv")
test = pd.read_csv("./test.csv")

In [53]:
label_train = train["label"]
target_train = train.drop(labels="label",axis=1)

In [54]:
#changing lists in np.arrays
target_train = np.array(target_train.values)
label_train = np.array(label_train.values)
print("label train data in np array")
print(label_train)
print(type(label_train))

label train data in np array
[1 0 1 ... 7 6 9]
<class 'numpy.ndarray'>


In [55]:
target_train, target_val, label_train, label_val = train_test_split(target_train, label_train, test_size=0.33, random_state=42)

In [56]:
dt = tree.DecisionTreeClassifier()
dt.fit(target_train, label_train)
label_pred = dt.predict(target_val)
print(label_pred[0:20], ".....")
print(label_val[0:20], ".....")
print(metrics.accuracy_score(label_val, label_pred))

[8 1 9 9 8 2 2 7 7 1 5 3 1 2 7 9 3 3 6 4] .....
[8 1 9 9 8 6 2 2 7 1 6 3 1 2 7 4 3 3 6 4] .....
0.8463203463203464


In [59]:
print(test.values)
target_test = np.array(test.values)
print(target_test)

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


In [60]:
test_predict = dt.predict(target_test)
print(test_predict)

[2 2 9 ... 3 9 2]


In [62]:
results = pd.Series(test_predict,name="Label")

submission = pd.concat([pd.Series(range(1,28001),name = "ImageId"),results],axis = 1)

submission.to_csv("decisionTree_datagen.csv",index=False)

In [ ]:
#SCORE ON KAGGLE: 0.84242